name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**.cs'
      - 'examples/'
      - '.npmignore'
      - '.gitignore'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test-ci
      - name: Generating coverage badges
        if: github.ref == 'refs/heads/master'
        uses: jpb06/jest-badges-action@latest
        with:
          branches: master
      - name: Pushing generated files
        if: github.ref == 'refs/heads/master'
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'dist/ -f'
          message: 'Update generated files'
